[workspace]
resolver = "2"
members = ["server", "client", "wisp"]

[patch.crates-io]
rustls-pki-types = { git = "https://github.com/r58Playz/rustls-pki-types" }

[profile.release]
lto = true
opt-level = 3
