[package]
name = "wisp-mux"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
dashmap = "5.5.3"
fastwebsockets = { version = "0.6.0", features = ["unstable-split"], optional = true }
futures = "0.3.30"
futures-util = "0.3.30"
tokio = { version = "1.35.1", optional = true }

[features]
fastwebsockets = ["dep:fastwebsockets", "dep:tokio"]
