[package]
name = "wisp-mux"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
fastwebsockets = { version = "0.6.0", optional = true }
futures = "0.3.30"
futures-util = "0.3.30"

[features]
fastwebsockets = ["dep:fastwebsockets"]
