[package]
name = "wstcp-server"
version = "1.0.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.0"
hyper = { version = "1.1.0", features = ["server", "http1"] }
hyper-util = { version = "0.1.2", features = ["tokio"] }
rusty-penguin = { version = "0.5.3", default-features = false }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "net", "macros"] }
tokio-native-tls = "0.3.1"
tokio-tungstenite = "0.21.0"
